import { fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import { PreviewApp } from './PreviewApp';
function route(path: string) { window.history.replaceState(null, '', path); window.dispatchEvent(new HashChangeEvent('hashchange')); }
afterEach(() => window.history.replaceState(null, '', '/'));
describe('student profile editing', () => {
  it('cancels without changing the profile', () => { route('#/students/s2'); render(<PreviewApp />); fireEvent.click(screen.getByRole('button', { name: '编辑资料' })); fireEvent.change(screen.getByLabelText('姓名'), { target: { value: '改过的名字' } }); fireEvent.click(screen.getByRole('button', { name: '取消' })); expect(screen.getByRole('heading', { name: '王浩然' })).toBeInTheDocument(); });
  it('rejects blank trimmed fields', () => { route('#/students/s2'); render(<PreviewApp />); fireEvent.click(screen.getByRole('button', { name: '编辑资料' })); fireEvent.change(screen.getByLabelText('姓名'), { target: { value: '   ' } }); fireEvent.click(screen.getByRole('button', { name: '保存修改' })); expect(screen.getByRole('alert')).toHaveTextContent('不能为空'); expect(screen.getByRole('dialog')).toBeInTheDocument(); });
  it('rejects a blank grade after trimming', () => { route('#/students/s2'); render(<PreviewApp />); fireEvent.click(screen.getByRole('button', { name: '编辑资料' })); fireEvent.change(screen.getByLabelText('年级'), { target: { value: '   ' } }); fireEvent.click(screen.getByRole('button', { name: '保存修改' })); expect(screen.getByRole('alert')).toHaveTextContent('不能为空'); });
  it('keeps id, balance and notes while renaming and links related views', () => { route('#/students/s2'); render(<PreviewApp />); fireEvent.click(screen.getByRole('button', { name: '编辑资料' })); fireEvent.change(screen.getByLabelText('姓名'), { target: { value: '王浩然（已更新）' } }); fireEvent.change(screen.getByLabelText('年级'), { target: { value: '初一' } }); fireEvent.click(screen.getByRole('button', { name: '保存修改' })); expect(screen.getByRole('heading', { name: '王浩然（已更新）' })).toBeInTheDocument(); expect(screen.getByText('2')).toBeInTheDocument(); expect(screen.getByText('课时余额较低，请留意')).toBeInTheDocument(); fireEvent.click(screen.getByRole('link', { name: '缴费课时' })); expect(screen.getByText('王浩然（已更新）')).toBeInTheDocument(); });
  it('summarizes small groups without names and reveals names in details', () => { route('#/students/s2'); render(<PreviewApp />); expect(screen.getAllByText('对象：小班 · 2 人').length).toBeGreaterThan(0); expect(screen.queryByText(/对象：.*王浩然/)).not.toBeInTheDocument(); fireEvent.click(screen.getAllByRole('button', { name: '查看详情' })[0]); expect(screen.getByText('王浩然、张思远')).toBeInTheDocument(); });
  it('uses the updated name in the linked schedule detail', () => { route('#/students/s2'); render(<PreviewApp />); fireEvent.click(screen.getByRole('button', { name: '编辑资料' })); fireEvent.change(screen.getByLabelText('姓名'), { target: { value: '王浩然新名' } }); fireEvent.click(screen.getByRole('button', { name: '保存修改' })); fireEvent.click(screen.getAllByRole('button', { name: '查看详情' })[0]); expect(screen.getByText('王浩然新名、张思远')).toBeInTheDocument(); });
});
