import { FormEvent, ReactNode, useMemo, useState } from 'react';
import { PreviewActions, studentName } from './PreviewApp';
import { Schedule, Student, today as fallbackToday } from './data';
import { dateAdd, schedulesInRange } from './recurrence';
import { openScheduleDetails } from './ScheduleDetails';
import { NewScheduleForm } from './ScheduleForm';
import { usePreviewState } from './ui-state';
import './students-edit.css';
import { formatDate } from '../shared/date-format';
import { commitAction } from './action-result';

function inStudentProjection(item: Schedule, studentId: string) { return item.participants.includes(studentId); }

export function StudentPages({ actions, studentId, recordPanel }: { actions: PreviewActions; studentId?: string; recordPanel?: (studentId: string) => ReactNode }) { const student = actions.data.students.find((item) => item.id === studentId); return student ? <StudentDetail key={student.id} actions={actions} student={student} recordPanel={recordPanel} /> : <StudentList actions={actions} />; }

function StudentList({ actions }: { actions: PreviewActions }) {
  const [query, setQuery] = usePreviewState(actions, 'students.query', ''); const [grade, setGrade] = usePreviewState(actions, 'students.grade', '');
  const grades = [...new Set(actions.data.students.map((item) => item.grade))];
  const filtered = useMemo(() => actions.data.students.filter((item) => `${item.name}${item.grade}`.includes(query.trim()) && (!grade || item.grade === grade)), [actions.data.students, grade, query]);
  const newStudent = () => actions.open('新增学生', <StudentForm onCancel={actions.close} onSave={(name, studentGrade) => { if (actions.saveStudent) return commitAction(actions, () => actions.saveStudent!(name, studentGrade), () => { actions.close(); actions.toast('学生已添加'); }); actions.setData((old) => ({ ...old, students: [...old.students, { id: `s-${Date.now()}`, name, grade: studentGrade, balance: 0, notes: [] }] })); actions.close(); actions.toast('学生已添加'); }} />);
  const editStudent = (student: Student) => actions.open(`编辑学生 · ${student.name}`, <StudentForm student={student} onCancel={actions.close} onSave={(name, studentGrade) => saveStudent(actions, student, name, studentGrade)} />);
  return <section className="page preview-page"><header className="page-header"><div><h1>我的学生</h1><p>共 {actions.data.students.length} 位学生</p></div><button className="button primary" onClick={newStudent}>+ 新增学生</button></header><div className="student-filters"><label className="search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索学生姓名…" aria-label="搜索学生" /></label><label className="grade-filter">年级<select value={grade} onChange={(event) => setGrade(event.target.value)}><option value="">全部年级</option>{grades.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><div className="white-card student-list">{filtered.map((student) => <div className="student-row" key={student.id}><a href={`#/students/${student.id}`}><b className="avatar">{student.name.slice(0, 1)}</b><span><strong>{student.name}</strong><small>{student.grade}</small></span><em>{student.balance} 课时</em><i>›</i></a><button className="button secondary small" onClick={() => editStudent(student)} aria-label={`编辑${student.name}`}>编辑</button></div>)}{!filtered.length && <p className="empty">没有匹配的学生</p>}</div></section>;
}

function saveStudent(actions: PreviewActions, student: Student, name: string, grade: string) { if (actions.saveStudent) return commitAction(actions, () => actions.saveStudent!(name, grade, student.id), () => { actions.close(); actions.toast('学生资料已更新'); }); actions.setData((old) => ({ ...old, students: old.students.map((item) => item.id === student.id ? { ...item, name, grade } : item) })); actions.close(); actions.toast('学生资料已更新'); }

function StudentForm({ student, onCancel, onSave }: { student?: Student; onCancel: () => void; onSave: (name: string, grade: string) => void }) {
  const [name, setName] = useState(student?.name || ''); const [grade, setGrade] = useState(student?.grade || ''); const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); const cleanName = name.trim(); const cleanGrade = grade.trim(); if (!cleanName || !cleanGrade) return setError('姓名和年级不能为空。'); setError(''); onSave(cleanName, cleanGrade); };
  return <form className="student-edit-form" onSubmit={submit}><label>姓名<input autoFocus value={name} onChange={(event) => setName(event.target.value)} aria-label="姓名" /></label><label>年级<input value={grade} onChange={(event) => setGrade(event.target.value)} aria-label="年级" /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onCancel}>取消</button><button className="button primary">{student ? '保存修改' : '保存学生'}</button></div></form>;
}

function StudentDetail({ actions, student, recordPanel }: { actions: PreviewActions; student: Student; recordPanel?: (studentId: string) => ReactNode }) {
  const today = actions.data.businessDate || fallbackToday;
  const [record, setRecord] = usePreviewState(actions, `student.record.${student.id}`, ''); const [recordError, setRecordError] = useState(''); const [showAll, setShowAll] = useState(false); const projected = schedulesInRange(actions.data, today, dateAdd(today, 30)).filter((item) => inStudentProjection(item, student.id)); const future = projected.filter((item) => item.status === '已排期').sort((a, b) => `${a.day}${a.start}`.localeCompare(`${b.day}${b.start}`)); const visibleFuture = showAll ? future : future.slice(0, 3); const historical = actions.data.schedules.filter((item) => item.status === '已完成' && inStudentProjection(item, student.id)).sort((a, b) => `${a.day}${a.start}`.localeCompare(`${b.day}${b.start}`)); const cancelled = actions.data.schedules.filter((item) => item.status === '已取消' && inStudentProjection(item, student.id)).sort((a, b) => `${a.day}${a.start}`.localeCompare(`${b.day}${b.start}`)); const [showCancelled, setShowCancelled] = useState(false); const completions = actions.data.completionRecords.filter((item) => item.studentId === student.id);
  const edit = () => actions.open(`编辑学生 · ${student.name}`, <StudentForm student={student} onCancel={actions.close} onSave={(name, grade) => saveStudent(actions, student, name, grade)} />);
  const saveRecord = () => { if (!record.trim()) return setRecordError('请输入记录内容。'); if (actions.prepareRecord) return commitAction(actions, () => actions.prepareRecord!(student.id, record.trim(), () => { setRecord(''); setRecordError(''); })); actions.setData((old) => ({ ...old, students: old.students.map((item) => item.id === student.id ? { ...item, notes: [record.trim(), ...item.notes] } : item) })); setRecord(''); setRecordError(''); actions.toast('记录已保存'); };
  const openSchedule = () => actions.open('新增排期', <NewScheduleForm actions={actions} initialStudentId={student.id} initialDay={today} />);
  return <section className="page preview-page"><a className="back" href="#/students">‹ 返回学生</a><div className="student-detail-layout"><aside className="student-profile"><b className="avatar large">{student.name.slice(0, 1)}</b><h1>{student.name}</h1><p>{student.grade}</p><strong>{student.balance}<small> 课时余额</small></strong><div className="button-row"><button className="button secondary" onClick={edit}>编辑资料</button><button className="button secondary" onClick={openSchedule}>安排排期</button></div></aside><section className="white-card student-timeline"><section className="student-record-entry"><h2>新增记录</h2><label className="sr-only" htmlFor="record">新增记录</label><textarea id="record" value={record} onChange={(event) => { setRecord(event.target.value); setRecordError(''); }} placeholder="记录一条备注…" />{recordError && <p className="form-error" role="alert">{recordError}</p>}<button className="button secondary" onClick={saveRecord}>保存记录</button></section>{recordPanel ? recordPanel(student.id) : <section className="saved-records"><h2>已保存记录</h2>{student.notes.length ? <div className="note-list">{student.notes.map((note, index) => <p key={`${note}-${index}`}>{note}</p>)}</div> : <p className="empty">暂无已保存记录</p>}</section>}<section><h2>未来排期</h2>{visibleFuture.map((item) => <ScheduleSummary key={item.id} item={item} actions={actions} student={student} />)}{future.length > 3 && <button className="button secondary small schedule-expand" onClick={() => setShowAll((value) => !value)}>{showAll ? '收起排期' : `展开全部 ${future.length} 次排期`}</button>}{!future.length && <p className="empty">暂无未来排期</p>}</section><section className="timeline-history"><h2>历史完成</h2>{historical.length ? historical.map((item) => <ScheduleSummary key={item.id} item={item} actions={actions} student={student} />) : <p className="empty">暂无历史完成课程</p>}<h3>课时流水</h3>{completions.length ? completions.map((item) => <div className="compact-schedule" key={item.id}><b>完成课时记录 · {formatDate(item.date)}</b><small>本次余额：{item.before} → {item.after} 课时</small></div>) : <p className="empty">暂无课时流水</p>}</section><section className="cancelled-history"><button className="section-toggle" aria-expanded={showCancelled} onClick={() => setShowCancelled((value) => !value)}>已取消课程（{cancelled.length}）</button>{showCancelled && (cancelled.length ? cancelled.map((item) => <ScheduleSummary key={item.id} item={item} actions={actions} student={student} />) : <p className="empty">暂无已取消课程</p>)}</section></section></div></section>;
}

function ScheduleSummary({ item, actions, student }: { item: Schedule; actions: PreviewActions; student: Student }) { const audience = item.format === '小班' ? `小班 · ${item.participants.length} 人` : student.name; return <article className="compact-schedule schedule-summary"><div className="schedule-tags"><span>时间：{formatDate(item.day)} {item.start}–{item.end}</span><span>对象：{audience}</span><span>地点：{item.location}</span></div><button className="button text-button" onClick={() => openScheduleDetails(actions, item)}>查看详情</button></article>; }
